CREATE TYPE "QuizQuestionType" AS ENUM ('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TRUE_FALSE', 'FILL_BLANK', 'CODE');

ALTER TABLE "Quiz"
  ADD COLUMN IF NOT EXISTS "instructions" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "difficulty" "Difficulty" NOT NULL DEFAULT 'EASY',
  ADD COLUMN IF NOT EXISTS "timeLimitMinutes" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "randomizeQuestions" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "randomizeAnswers" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "QuizQuestion"
  ADD COLUMN IF NOT EXISTS "type" "QuizQuestionType" NOT NULL DEFAULT 'SINGLE_CHOICE',
  ADD COLUMN IF NOT EXISTS "acceptedAnswers" JSONB,
  ADD COLUMN IF NOT EXISTS "hint" TEXT,
  ADD COLUMN IF NOT EXISTS "points" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS "difficulty" "Difficulty" NOT NULL DEFAULT 'EASY',
  ADD COLUMN IF NOT EXISTS "codeSnippet" TEXT,
  ADD COLUMN IF NOT EXISTS "mediaUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE "QuizQuestion"
  ALTER COLUMN "correctAnswer" TYPE JSONB USING to_jsonb("correctAnswer");

ALTER TABLE "QuizAttempt"
  ADD COLUMN IF NOT EXISTS "percentage" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "correctCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "incorrectCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "completedAt" TIMESTAMP(3);
