import { ArrowLeft, Plus, Save, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { adminService, type AdminQuiz, type AdminQuizQuestion } from "../services/adminService";

const blankQuiz = { title: "", description: "", instructions: "", difficulty: "EASY" as "EASY" | "MEDIUM" | "HARD", passingPercentage: 70, timeLimitMinutes: 0, published: false, isActive: true };
const blankQuestion = { type: "SINGLE_CHOICE" as AdminQuizQuestion["type"], prompt: "", optionsText: "", correctText: "", explanation: "", hint: "", points: 10, order: 1 };
const messageFrom = (error: unknown) => error instanceof Error ? error.message : "The change could not be saved.";

export function AdminQuizzesPage() {
  const [quizzes, setQuizzes] = useState<AdminQuiz[]>([]);
  const [selected, setSelected] = useState<AdminQuiz | null>(null);
  const [quizDraft, setQuizDraft] = useState(blankQuiz);
  const [questionDraft, setQuestionDraft] = useState(blankQuestion);
  const [editingQuestion, setEditingQuestion] = useState<string | null>(null);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [saving, setSaving] = useState(false);

  async function refresh() { const rows = await adminService.quizzes(); setQuizzes(rows); return rows; }
  async function select(id: string) {
    const quiz = await adminService.quiz(id); setSelected(quiz); setQuizDraft({ title: quiz.title, description: quiz.description, instructions: quiz.instructions, difficulty: quiz.difficulty, passingPercentage: quiz.passingPercentage, timeLimitMinutes: quiz.timeLimitMinutes, published: quiz.published, isActive: quiz.isActive }); setQuestionDraft({ ...blankQuestion, order: quiz.questions.length + 1 }); setEditingQuestion(null);
  }
  useEffect(() => { refresh().catch((cause) => setError(messageFrom(cause))); }, []);

  async function saveQuiz() {
    setSaving(true); setError("");
    try { const saved = selected ? await adminService.updateQuiz(selected.id, quizDraft) : await adminService.createQuiz(quizDraft); await refresh(); await select(saved.id); setNotice(selected ? "Quiz updated." : "Quiz created."); }
    catch (cause) { setError(messageFrom(cause)); } finally { setSaving(false); }
  }
  async function removeQuiz(quiz: AdminQuiz) { if (!window.confirm(`Delete "${quiz.title}" and all its questions and attempts?`)) return; try { await adminService.deleteQuiz(quiz.id); setSelected(null); setQuizDraft(blankQuiz); await refresh(); setNotice("Quiz deleted."); } catch (cause) { setError(messageFrom(cause)); } }
  function editQuestion(question: AdminQuizQuestion) { setEditingQuestion(question.id); setQuestionDraft({ type: question.type, prompt: question.prompt, optionsText: question.options.map(String).join("\n"), correctText: Array.isArray(question.correctAnswer) ? question.correctAnswer.join(",") : String(question.correctAnswer ?? ""), explanation: question.explanation ?? "", hint: question.hint ?? "", points: question.points, order: question.order }); }
  async function saveQuestion() {
    if (!selected) return;
    const options = questionDraft.optionsText.split(/\r?\n|,/).map((item) => item.trim()).filter(Boolean);
    const rawCorrect = questionDraft.correctText.split(",").map((item) => item.trim()).filter(Boolean);
    const correctAnswer = questionDraft.type === "MULTIPLE_CHOICE" ? rawCorrect.map((item) => Number.isNaN(Number(item)) ? item : Number(item)) : (Number.isNaN(Number(rawCorrect[0])) ? rawCorrect[0] : Number(rawCorrect[0]));
    setSaving(true); setError("");
    try { const input = { type: questionDraft.type, prompt: questionDraft.prompt, options, correctAnswer, explanation: questionDraft.explanation || null, hint: questionDraft.hint || null, points: questionDraft.points, order: questionDraft.order, difficulty: "EASY" as const, isActive: true }; if (editingQuestion) await adminService.updateQuizQuestion(editingQuestion, input); else await adminService.createQuizQuestion(selected.id, input); await select(selected.id); setNotice(editingQuestion ? "Question updated." : "Question added."); }
    catch (cause) { setError(messageFrom(cause)); } finally { setSaving(false); }
  }
  async function removeQuestion(question: AdminQuizQuestion) { if (!window.confirm("Delete this question?")) return; try { await adminService.deleteQuizQuestion(question.id); await select(selected!.id); setNotice("Question deleted."); } catch (cause) { setError(messageFrom(cause)); } }

  return <main className="content-page section dashboard-page admin-course-page">
    <Link className="back-link" to="/admin"><ArrowLeft size={16} /> Admin dashboard</Link>
    <div className="eyebrow">PYPATH ADMINISTRATION</div><h1>Quiz <span>studio.</span></h1><p className="content-intro">Create, validate, publish, and maintain learner quizzes.</p>
    {error && <div className="form-error" role="alert">{error}</div>}{notice && <div className="admin-notice" role="status">{notice}</div>}
    <div className="admin-course-layout"><aside className="admin-course-list"><div className="admin-course-list-heading"><h2>Quizzes</h2><button className="button button-dark" type="button" onClick={() => { setSelected(null); setQuizDraft(blankQuiz); }}><Plus size={15} /> New</button></div>{quizzes.map((quiz) => <div className={`admin-course-list-item${selected?.id === quiz.id ? " selected" : ""}`} key={quiz.id}><button className="admin-course-select" type="button" onClick={() => void select(quiz.id)}><strong>{quiz.title}</strong><span>{quiz.published ? "Published" : "Draft"} · {quiz._count?.questions ?? 0} questions</span></button><button className="icon-action danger-action" type="button" aria-label={`Delete ${quiz.title}`} onClick={() => void removeQuiz(quiz)}><Trash2 size={15} /></button></div>)}{!quizzes.length && <p className="muted">No quizzes yet.</p>}</aside>
      <section className="admin-course-editor"><div className="admin-editor-card"><div className="admin-editor-title"><h2>{selected ? "Quiz details" : "Create a quiz"}</h2></div><div className="admin-form-grid"><label className="admin-field">Title<input required minLength={2} value={quizDraft.title} onChange={(e) => setQuizDraft({ ...quizDraft, title: e.target.value })} /></label><label className="admin-field">Difficulty<select value={quizDraft.difficulty} onChange={(e) => setQuizDraft({ ...quizDraft, difficulty: e.target.value as typeof quizDraft.difficulty })}><option>EASY</option><option>MEDIUM</option><option>HARD</option></select></label><label className="admin-field">Passing percentage<input type="number" min="0" max="100" value={quizDraft.passingPercentage} onChange={(e) => setQuizDraft({ ...quizDraft, passingPercentage: Number(e.target.value) })} /></label><label className="admin-field">Time limit (minutes)<input type="number" min="0" value={quizDraft.timeLimitMinutes} onChange={(e) => setQuizDraft({ ...quizDraft, timeLimitMinutes: Number(e.target.value) })} /></label><label className="admin-field full-field">Description<textarea rows={2} value={quizDraft.description} onChange={(e) => setQuizDraft({ ...quizDraft, description: e.target.value })} /></label><label className="admin-field full-field">Instructions<textarea rows={2} value={quizDraft.instructions} onChange={(e) => setQuizDraft({ ...quizDraft, instructions: e.target.value })} /></label></div><label className="admin-check"><input type="checkbox" checked={quizDraft.published} onChange={(e) => setQuizDraft({ ...quizDraft, published: e.target.checked })} /> Publish quiz</label><button className="button button-dark" type="button" disabled={saving} onClick={() => void saveQuiz()}><Save size={15} /> Save quiz</button></div>
        {selected && <section className="admin-editor-card curriculum-editor"><div className="admin-editor-title"><h2>Questions</h2></div>{selected.questions.map((question) => <div className="admin-lesson-row" key={question.id}><div><strong>{question.order}. {question.prompt}</strong><span>{question.type} · {question.points} points</span></div><div className="admin-row-actions"><button className="table-action" type="button" onClick={() => editQuestion(question)}>Edit</button><button className="icon-action danger-action" type="button" aria-label="Delete question" onClick={() => void removeQuestion(question)}><Trash2 size={15} /></button></div></div>)}<div className="admin-inline-form"><h4>{editingQuestion ? "Edit question" : "Add a question"}</h4><div className="admin-form-grid"><label className="admin-field">Type<select value={questionDraft.type} onChange={(e) => setQuestionDraft({ ...questionDraft, type: e.target.value as typeof questionDraft.type })}><option>SINGLE_CHOICE</option><option>MULTIPLE_CHOICE</option><option>TRUE_FALSE</option><option>FILL_BLANK</option><option>CODE</option></select></label><label className="admin-field">Points<input type="number" min="0" max="10000" value={questionDraft.points} onChange={(e) => setQuestionDraft({ ...questionDraft, points: Number(e.target.value) })} /></label><label className="admin-field">Order<input type="number" min="1" value={questionDraft.order} onChange={(e) => setQuestionDraft({ ...questionDraft, order: Number(e.target.value) })} /></label><label className="admin-field full-field">Question<textarea required rows={3} value={questionDraft.prompt} onChange={(e) => setQuestionDraft({ ...questionDraft, prompt: e.target.value })} /></label><label className="admin-field full-field">Options (one per line)<textarea rows={3} value={questionDraft.optionsText} onChange={(e) => setQuestionDraft({ ...questionDraft, optionsText: e.target.value })} /></label><label className="admin-field">Correct answer(s)<input required placeholder="0 or 0,2" value={questionDraft.correctText} onChange={(e) => setQuestionDraft({ ...questionDraft, correctText: e.target.value })} /></label><label className="admin-field">Hint<input value={questionDraft.hint} onChange={(e) => setQuestionDraft({ ...questionDraft, hint: e.target.value })} /></label><label className="admin-field full-field">Explanation<textarea rows={2} value={questionDraft.explanation} onChange={(e) => setQuestionDraft({ ...questionDraft, explanation: e.target.value })} /></label></div><div className="admin-row-actions"><button className="button button-dark" type="button" disabled={saving} onClick={() => void saveQuestion()}><Save size={15} /> Save question</button>{editingQuestion && <button className="button button-light" type="button" onClick={() => { setEditingQuestion(null); setQuestionDraft({ ...blankQuestion, order: selected.questions.length + 1 }); }}><X size={15} /> Cancel</button>}</div></div></section>}
      </section></div>
  </main>;
}
